### ISSUE TITLE
Invalid parameter: redirect_uri

### ISSUE THREAD

**Issue by alirizaaribas-ibg** [bcgsc/pori#49]
**Describe the bug**
When accessing graphkb_client latest version, page redirects([to this link](http://10.100.120.219:8888/auth/realms/PORI/protocol/openid-connect/auth?client_id=GraphKB&redirect_uri=http%3A%2F%2F10.100.120.219%3A5000%2Flogin&state=b05c79d6-574d-40ae-8206-5106f884a8ab&response_mode=fragment&response_type=code&scope=openid&nonce=3bad6b15-b09a-4e92-8fe0-900bd80d8921)) and show an error. `10.100.120.219` is our server internal ip address. 

`Invalid parameter: redirect_uri`
![image](https://user-images.githubusercontent.com/55430656/164171211-af4d0095-f24d-4d1e-abc0-e99af05dd8e7.png)

I wanted to put graphkb(latest) on production.

**To Reproduce**
Steps to reproduce the behaviour:

1. Run command  `docker-compose -f custom_docker.yml up -d` 
2. Access grapkb_client at `http://10.100.120.219:5000/`
3. Page shows error

here is my custom_docker.yml: 
[custom_docker.txt](https://github.com/bcgsc/pori_graphkb_client/files/8519196/custom_docker.txt)

**Expected behaviour**
Graphkb login screen should be visible.

**Versions (please complete the following information):**

- OS: centos 7
- NodeJS: 16.14.2
- Version: latest
- OrientDB Version: 3.0

**Additional context**
I don't use HTTPS. My first aim is to run PORI without **any** error. Then I hope to use HTTPS.

**Comment by creisle** [comment]
I have moved this issue to the main repo and added a documentation label as I will add instructions on how to do this to the main documentation as well as here to help future users encountering the same issue

**Comment by alirizaaribas-ibg** [comment]
@creisle Thank you. Now it works well.

**Comment by creisle** [comment]
@alirizaaribas-ibg did this also resolve your comment on https://github.com/bcgsc/pori_graphkb_loader/issues/70#issuecomment-1098041721 or is that still outstanding?

**Comment by alirizaaribas-ibg** [comment]
@creisle resolved. Thank you for your attention.
